### ISSUE TITLE
having an issue with logs

### ISSUE THREAD

**Issue by Darshil182** [sapphonie/SM-neocurl-ext#5]
logs don't upload the chat says "uploading logs" but doesnt upload
the log files do exist in the folder
there is no error message either

**Comment by sapphonie** [comment]
please run this in server console and post the output

`version; plugin_print; meta version; meta list; sm version; sm exts list; sm plugins list`

thanks

**Comment by Darshil182** [comment]
Build Label: 8622567 # Uniquely identifies each build
Network PatchVersion: 8622567 # Determines client and server compatibility
Protocol version: 24 # High level network protocol version
Server version: 8622567
Server AppID: 232250
Loaded plugins:

0: "Metamod:Source 1.11.0-dev+1148"
1: "srctv+"

Metamod:Source Version Information
Metamod:Source version 1.11.0-dev+1148
Plugin interface version: 16:14
SourceHook version: 5:5
Loaded As: Valve Server Plugin
Compiled on: Jun 24 2022 14:35:52
Built from: https://github.com/alliedmodders/metamod-source/commit/4bdc218
Build ID: 1148:4bdc218
http://www.metamodsource.net/
Listing 6 plugins:
[01] SourceMod (1.11.0.6954) by AlliedModders LLC
[02] TF2 Tools (1.11.0.6954) by AlliedModders LLC
[03] SDK Hooks (1.11.0.6954) by AlliedModders LLC
[04] SDK Tools (1.11.0.6954) by AlliedModders LLC
[05] SteamWorks Extension (1.2.3) by Kyle Sanderson
[06] DHooks (1.11.0.6954) by AlliedModders LLC
SourceMod Version Information:
SourceMod Version: 1.11.0.6954
SourcePawn Engine: 1.11.0.6954, jit-x86 (build 1.11.0.6954)
SourcePawn API: v1 = 5, v2 = 16
Compiled on: Feb 2 2024 13:43:38
Built from: https://github.com/alliedmodders/sourcemod/commit/9bcfd45f
Build ID: 6954:9bcfd45f
http://www.sourcemod.net/
[SM] Displaying 15 extensions:
[01] Automatic Updater (1.11.0.6954): Updates SourceMod gamedata files
[02] Webternet (1.11.0.6954): Extension for interacting with URLs
[03] NEO cURL Extension (2.0.1): NEO cURL Extension
[04] TF2 Tools (1.11.0.6954): TF2 extended functionality
[05] BinTools (1.11.0.6954): Low-level C/C++ Calling API
[06] SDK Hooks (1.11.0.6954): Source SDK Hooks
[07] SDK Tools (1.11.0.6954): Source SDK Tools
[08] Top Menus (1.11.0.6954): Creates sorted nested menus
[09] Regex (1.11.0.6954): Provides regex natives for plugins
[10] Client Preferences (1.11.0.6954): Saves client preference settings
[11] SQLite (1.11.0.6954): SQLite Driver
[12] <OPTIONAL> file "steamtools.ext.dll": The specified module could not be found.

[13] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[14] DHooks (1.11.0.6954): Dynamic Hooks
[15] <OPTIONAL> file "system2.ext.dll": The specified module could not be found.

[SM] Listing 41 plugins:
01 "Admin File Reader" (1.11.0.6954) by AlliedModders LLC
02 "Admin Help" (1.11.0.6954) by AlliedModders LLC
03 "Admin Menu" (1.11.0.6954) by AlliedModders LLC
04 "AFK Detector" (1.1.1) by F2
05 "Anti-Flood" (1.11.0.6954) by AlliedModders LLC
06 "Basic Ban Commands" (1.11.0.6954) by AlliedModders LLC
07 "Basic Chat" (1.11.0.6954) by AlliedModders LLC
08 "Basic Comm Control" (1.11.0.6954) by AlliedModders LLC
09 "Basic Commands" (1.11.0.6954) by AlliedModders LLC
10 "Basic Info Triggers" (1.11.0.6954) by AlliedModders LLC
11 "Basic Votes" (1.11.0.6954) by AlliedModders LLC
12 "[TF2] Boss Spawn" (1.0.0) by (AMS-$)ILOVEPIE & Geit & DarthNinja
13 "MGEMod" (2.3.3) by Lange & Cprice; based on kAmmomod by Krolus, Modified by PepperKick, Extra modiftications by Nacho Replay and Obla
14 "Client Preferences" (1.11.0.6954) by AlliedModders LLC
15 "[Any] Arbitrary Chat Colours" (1.1.0.SCP) by DarthNinja
16 "cURL self test" (1.1.0.0) by Raydan
17 "[Source 2013] Custom Chat Colors" (3.1.0) by Dr. McKay
18 "demos.tf uploader" (0.3.2-beta-sappho) by Icewind / sappho.io
19 "Fun Commands" (1.11.0.6954) by AlliedModders LLC
20 "Fun Commands X" (2.5) by Spazman0 and Arg!
21 "Fun Votes" (1.11.0.6954) by AlliedModders LLC
22 "Logs.TF Uploader" (2.3.2) by F2, fixed by stephanie
23 "Medic Stats" (1.3.6) by F2, fixed by stephanie
24 "Improved Pause Command" (1.4.2) by Aad
25 "Player Commands" (1.11.0.6954) by AlliedModders LLC
26 "TF2 Projectile Collision Fix" (1.1.0) by Bakugo
27 "Record SourceTV" (1.1.1) by F2
28 "Reserved Slots" (1.11.0.6954) by AlliedModders LLC
29 "Resize Players" (1.5.1) by 11530
30 "Restore Score" (1.1.3) by F2, edited by stephanie
31 "RGL.gg QoL Tweaks" (1.4.3) by Stephanie, Aad
32 "Simple Chat Processor (Redux)" (2.3.0) by Simple Plugins, Mini
33 "Simple SourceMod Plugins Core Plugin" (1.0.$Revision: 90 $) by Simple SourceMod Plugins
34 "REGEX word filter" (1.2) by Twilight Suzuka
35 "SOAP Tournament" (3.8.5) by Lange - maintained by sappho.io
36 "Sound Commands" (1.11.0.6954) by AlliedModders LLC
37 "Supplemental Stats v2" (2.3.3) by F2 (v1 by Jean-Denis Caron), fixed by stephanie
38 "TeamPrefixes" (1.1) by Sawr
39 "TF2 Competitive Fixes" (1.16.14) by ldesgoui
40 "Themes" (0.8) by J-Factor
41 <Failed> "SOAP TF2 Deathmatch" (4.4.5) by Icewind, MikeJS, Lange, Tondark - maintained by sappho.io
Errors:
soap_tf2dm.smx (SOAP TF2 Deathmatch): Cowardly refusing to load SOAP DM on an MGE map.

**Comment by sapphonie** [comment]
@Darshil182 Please update your F2 plugins with the ones from here:

https://github.com/F2/F2s-sourcemod-plugins/releases/latest

The versions that were "fixed by me" are no longer needed and lack critical updates that F2 has added, which would likely fix this issue.
